# Generated by Django 5.0.1 on 2024-03-12 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresstwo',
            name='address_one',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application.addressone'),
            preserve_default=False,
        ),
    ]
