# Generated by Django 5.0.1 on 2024-03-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_buses_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lines',
            name='itinerary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
